import os
from os import environ

from dotenv import load_dotenv

load_dotenv()

# SETTINGS
VERSION = environ["VERSION"]
ROUTE_PREFIX = "/api"

# DATABASES
REDIS_HOST = environ["REDIS_HOST"]
REDIS_PASSWORD = environ["REDIS_PASSWORD"]
REDIS_PORT = environ["REDIS_PORT"]

REDIS_KEY_STORAGE_DB = environ["REDIS_KEY_STORAGE_DB"]
REDIS_TRACEBACK_STORAGE_DB = environ["REDIS_TRACEBACK_STORAGE_DB"]

POSTGRES_HOST = environ["POSTGRES_HOST"]
POSTGRES_USER = environ["POSTGRES_USER"]
POSTGRES_PASSWORD = environ["POSTGRES_PASSWORD"]
POSTGRES_PORT = environ["POSTGRES_PORT"]
POSTGRES_DB = environ["POSTGRES_DB"]
POSTGRES_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
